# permissions for end users to view deployersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployerset-viewer-role
rules:
- apiGroups:
  - core.hybridapp.io
  resources:
  - deployersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.hybridapp.io
  resources:
  - deployersets/status
  verbs:
  - get
