# permissions for end users to edit deployersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployerset-editor-role
rules:
- apiGroups:
  - core.hybridapp.io
  resources:
  - deployersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.hybridapp.io
  resources:
  - deployersets/status
  verbs:
  - get
